baseURL = 'https://xpslogistics.netlify.app/'
languageCode = 'en-us'
title = 'XPS Logistics'

[sass]
  use_dart_sass = true

upload_dir = "assets/uploads"
public_path = "/uploads"
# disableKinds = [ "taxonomy", "term" ]

[taxonomies]
  category = "categories"
  # tag = "tags"

[pagination]
  pagerSize = 9

[ params ]
  version = "1738220434631"
  twic = "xpslogistics"
  share = "/uploads/xps-share-fallback.jpg"
  logo = "/uploads/joseph-pinder-logo.png"
  # Facebook App ID
  app_id = "223848628924279"
  error = true

  [params.social]
    facebook = "jsphpndr"
    instagram = "jsphpndr"
    linkedin = "jsphpndr"
    github = "jsphpndr"
    x = "jsphpndr"


[[menu.main]]
  identifier = "about"
  name = "Company"
  url = "/company/"
  weight = 3

[[menu.main]]
  identifier = "services"
  name = "Services"
  url = "/services/"
  weight = 3

[[menu.main]]
  parent = "services"
  name = "Freight Forwarding"
  url = "/services/freight-forwarding/"
  weight = 1

[[menu.main]]
  parent = "services"
  name = "Customs Brokerage"
  url = "/services/customs-brokerage/"
  weight = 2

[[menu.main]]
  parent = "services"
  name = "Warehousing"
  url = "/services/warehousing/"
  weight = 3

[[menu.main]]
  parent = "services"
  name = "Distribution"
  url = "/services/distribution/"
  weight = 4

[[menu.main]]
  identifier = "insights"
  name = "Insights"
  url = "/insights/"
  weight = 4

[[menu.main]]
  identifier = "contact"
  name = "Contact Us"
  url = "/contact-us/"
  weight = 5

# -------------------------------------------------
# POLICIES MENU
# -------------------------------------------------
# Defines the legal/utility links in the footer (bottom bar).
# - Includes Privacy Policy, Terms of Service, Cookie Policy, Accessibility.
# - Keeps compliance pages grouped and accessible sitewide.
# - Weights control left-to-right order in the footer.
# -------------------------------------------------

[[menu.policies]]
  identifier = "privacy-policy"
  name = "Privacy Policy"
  url = "/privacy-policy/"
  weight = 1

[[menu.policies]]
  identifier = "terms-of-service"
  name = "Terms of Service"
  url = "/terms-of-service/"
  weight = 2

[[menu.policies]]
  identifier = "cookie-policy"
  name = "Cookie Policy"
  url = "/cookie-policy/"
  weight = 3

[[menu.policies]]
  identifier = "accessibility-statement"
  name = "Accessibility Statement"
  url = "/accessibility-statement/"
  weight = 4


[markup]
  [markup.goldmark]
  
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false

      [markup.goldmark.parser.attribute]
        block = true

    # Links
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.link]
        enableDefault = true        

[security.funcs]
  getenv = ['^HUGO_', '^GA_TRACKING_ID$', '^META_PIXEL_ID$']


enableGitInfo = true

[sitemap]
  filename = "sitemap.xml"
  changefreq = "monthly"
  priority = 0.5